export const availableLanguagesMap = new Map([
  ["c", "C"],
  ["cpp", "C++"],
  ["cs", "C#"],
  ["dart", "Dart"],
  ["go", "Go"],
  ["java", "Java"],
  ["js", "JavaScript"],
  ["php", "PHP"],
  ["py", "Python"],
  ["rb", "Ruby"],
  ["rs", "Rust"],
  ["swift", "Swift"],
  ["ts", "TypeScript"],
  ["kt", "Kotlin"],
  ["scala", "Scala"],
  ["pl", "Perl"],
  ["hs", "Haskell"],
  ["lua", "Lua"],
  ["erl", "Erlang"],
  ["clj", "Clojure"],
  ["objc", "Objective-C"],
  ["asm", "Assembly"],
  ["sh", "Shell"],
  ["sql", "SQL"],
  ["html", "HTML"],
  ["css", "CSS"],
  ["r", "R"],
  ["m", "Matlab"],
  ["vb", "Visual Basic"],
  ["yaml", "YAML"],
  ["json", "JSON"],
  ["xml", "XML"],
  ["ini", "INI"],
  ["cfg", "Configuration"],
  ["conf", "Configuration"],
]);

export const availableLanguages = [
  "C",
  "C++",
  "C#",
  "Dart",
  "Go",
  "Java",
  "JavaScript",
  "PHP",
  "Python",
  "Ruby",
  "Rust",
  "Swift",
  "TypeScript",
  "Kotlin",
  "Scala",
  "Perl",
  "Haskell",
  "Lua",
  "Erlang",
  "Clojure",
  "Objective-C",
  "Assembly",
  "Shell",
  "SQL",
  "HTML",
  "CSS",
  "R",
  "Matlab",
  "Visual Basic",
  "YAML",
  "JSON",
  "XML",
  "INI",
  "Configuration",
];

export const getLanguageName = (language: string) => {
  return availableLanguagesMap.get(language);
};
